{
 "title": "Dashboard HTTP",
 "description": "Show stats from the kubernetes nginx ingress",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Number of Server Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_size_sum[5m])) by (service)",
     "legendFormat": "{{ service }} "
    }
   ]
  },
  {
   "title": "Server Responses By Http response code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_size_sum[5m])) by (status)",
     "legendFormat": "{{ status }} "
    }
   ]
  },
  {
   "title": "Server Responses By 4xx Http response code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_response_size_count{status=~\"4..\"}[5m])) by (service)",
     "legendFormat": "{{ service }} "
    }
   ]
  },
  {
   "title": "Server Responses By 5xx Http response code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Temps de réponse des services Backend",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_ingress_upstream_latency_seconds_sum",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}